# Generated by Django 3.2.6 on 2021-08-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
    ]
